### PR TITLE
Restart collectd service after installing a new version

### PR DESCRIPTION
**Pull request by yogeswaran**
When a new version of collectd is installed, collectd service is not restarted if there is no change to configuration.

### CODE REVIEW

**Comment by johnbellone** [comment]
There is a better way to do this. We can run notify if the package sub-resource is updated in the library.

**Comment by johnbellone** [comment]
Did this happen on certain platforms?

**Comment by yogeswaran** [comment]
This happens on RHEL5.

**Comment by johnbellone** [comment]
Can you try the latest version I pushed?

**Comment by johnbellone** [comment]
Let me know if this needs to be revisited.

**Pull request closed without merging**
